# Generated by Django 4.0.3 on 2022-03-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ManyToManyField(to='main_app.product'),
        ),
    ]
