# Generated by Django 4.0.3 on 2022-03-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_look'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
    ]
